# Generated by Django 3.2.7 on 2021-09-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
