# Generated by Django 3.2.7 on 2021-09-11 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20210911_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
