# Generated by Django 3.2.7 on 2021-09-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
